### PR TITLE
register native routines, push v2.1-13

### PR DESCRIPTION
**Pull request by ethanbass**
Register native routines to fix R CMD check note.

note:
File ‘VPdtw/libs/VPdtw.so’:
    Found no calls to: ‘R_registerRoutines’, ‘R_useDynamicSymbols’

  It is good practice to register native routines and to disable symbol
  search.

### CODE REVIEW

**Comment by ethanbass** [comment]
Hi,
I don't know if you're still maintaining the package much, but adding this file seems to fix the note generated by R CMD check. It's a really useful package by the way!! Thanks for developing this.

**Comment by david-clifford** [comment]
Thanks for getting in touch and helping keep the package up to date. Honestly I haven't used this in years. I'm glad to hear you find use in it. Thanks for your help.

**Comment by ethanbass** [comment]
very happy to help. I wonder if you would ever consider resubmitting the package to CRAN? I added VPdtw as a "suggestion" in my R package chromatographR which i am hoping to publish soon on CRAN but I would prefer to have it as a dependency if it was available through CRAN.

**Comment by david-clifford** [comment]
I have not considered it - for someone working with R on a regular basis I
guess it might be easy to keep up with the CRAN changes but I've not been
able to do this for the few packages I wrote. For the regress package
<https://cran.r-project.org/web/packages/regress/index.html> Karl Broman
took over the maintenance - you are welcome to do something similar here if
you wish.

-d

**Comment by ethanbass** [comment]
Thanks, mission accomplished! https://cran.r-project.org/web/packages/VPdtw/index.html

**Pull request merged**
